### ISSUE TITLE
Found 0 photos in a album

### ISSUE THREAD

**Issue by stefanogit** [faisalraja/flickrsmartsync#30]
Hi!
Recently I have a problem to sync 1 folder. Your script find the album but everytime it say me that is empty:
INFO:flickrsmartsync:Getting photos in set [2014-05 CUNADI]
INFO:flickrsmartsync:Found 0 photos
It happens only with that album (that contains 204 picture...).
I didn't edit the description or other stuff.
Any idea?
s.

PS
I run the 0.1.17 version on ubuntu 12.04

**Comment by leokury** [comment]
I have the same problem!

I run 0.1.18 on Windows 7

**Comment by faisalraja** [comment]
I'm not sure too. If there are other clues open another issue maybe. Thanks
