### ISSUE TITLE
Deletions

### ISSUE THREAD

**Issue by latitudehopper** [faisalraja/flickrsmartsync#38]
Does FSS delete from Flickr where the file is not available locally?
Also, if I change a file but the name is the same, will it update on Flickr?

**Comment by horstt** [comment]
Someone has worked on the option to do a one-way sync; mirror local to remote or mirror remote to local, but this hasn't been completed. Only the sync both ways has been factored in. I would love to have a sync from local to remote myself, but I am not really good with coding myself...
