### ISSUE TITLE
Memory consumption for larger files

### ISSUE THREAD

**Issue by pejobo** [faisalraja/flickrsmartsync#42]
I use this great tool to backup images automatically.
This is done on a Raspberry Pi in two steps (first copy from SD-Card to local USB-Drive, then upload to flickr). The second step fails for larger files (e.g. movies) because main memory is very limited on a pi. Each movie upload is retried a few times:

WARNING:flickrsmartsync:Retrying upload of 2015/2015-04/DJI00080.MP4 after error:
WARNING:flickrsmartsync:Retrying upload of 2015/2015-04/DJI00080.MP4 after error:
WARNING:flickrsmartsync:Retrying upload of 2015/2015-04/DJI00080.MP4 after error:
WARNING:flickrsmartsync:Retrying upload of 2015/2015-04/DJI00080.MP4 after error:
WARNING:flickrsmartsync:Retrying upload of 2015/2015-04/DJI00080.MP4 after error:
ERROR:flickrsmartsync:Failed upload of 2015/2015-04/DJI00080.MP4 after 5 retries

**Comment by pejobo** [comment]
I tried to replace the upload code with something stream based but so far I failed miserably due to my limited python knowledge :/

**Comment by cicero22** [comment]
+1

Suffering from the same issue too (Raspberry Pi + mounted SMB drive on a Windows machine). Is there any way to fix this?

**Comment by pejobo** [comment]
It's a problem of the included flickrapi package. I had a conversation with one of their core developers. He's accepting patches. Unfortunately the project is not hosted on github..
