### ISSUE TITLE
Album detection changed?

### ISSUE THREAD

**Issue by pejobo** [faisalraja/flickrsmartsync#46]
All my albums uploaded with version up to 0.18 have 

  album name = folder name (e.g. 2015-06)
  album comment = folder path (e.g. 2015/2015-06)

With 0.2.01 album name and album comment both are only folder name. With this name scheme folder to album matching no longer works and flickrsmartsync wants to upload my whole photos again :(

(This is on linux of course.)

**Comment by faisalraja** [comment]
hmm there shouldn't be any change like that, can you double check if you are running the script under the folder where 2015 exists and not in 2015 folder?

**Comment by pejobo** [comment]
Yes, my fault. I moved down one directory when "--starts-with 2015/2015-05/" didn't synced any photo.
Thanks for your quick feedback.
