### ISSUE TITLE
--starts-with option does not work with non-ascii directory parameter

### ISSUE THREAD

**Issue by vujevits** [faisalraja/flickrsmartsync#68]
I get the following logs for both new and existing folders:
INFO:flickrsmartsync:Getting photosets page 1
INFO:flickrsmartsync:Getting photosets page 2
INFO:flickrsmartsync:Found 0 photo sets
INFO:flickrsmartsync:Upload done

**Comment by faisalraja** [comment]
I just tested this, mine still works. But I also bumped master to pypi. Can you try to update and see if that changes anything.

**Comment by vujevits** [comment]
I updated, also removed and reinstalled, but it did not help. I tried it with a few directories, and it seems to be working with directory names containing only ascii characters. Of course that's just a guess, but it does not work with "2016.10 - Októberi Teó" and a few other examples. Last time I checked it worked.

**Comment by faisalraja** [comment]
I just tested it with that name and it still works. Give me a filename sample under that folder.

**Comment by vujevits** [comment]
nothing special with the filename: DSCF8841.JPG

**Comment by vujevits** [comment]
I tried with some other folders (with and without non english characters), and had the same results. More info about my setup:
macOS 10.12.1
python 2.7.10

**Comment by vujevits** [comment]
I started adding some loglines locally, it seems the issue is here:
https://github.com/faisalraja/flickrsmartsync/blob/895e7c5e967b5fcdc41d4d89160663ce330d635b/flickrsmartsync/local.py#L23

It rises when you are using --starts-with, and the parameter contains non-ascii character. It's not the directory, but the parameter. 
So I can:
flickrsmartsync --starts-with 2016\ -\ Te
but cannot:
flickrsmartsync --starts-with 2016\ -\ Teó

**Comment by faisalraja** [comment]
Mine still works, if your folder is 2016.10 I tested it with starts-with 2016.10\ -\ Teó
